### ISSUE TITLE
Intellisense fails with an "Illegal argument: value" error on hover

### ISSUE THREAD

**Issue by andrew-carroll** [mark-wiemer/vscode-autohotkey-plus-plus#16]
**Describe the bug**
When hovering over any AHK function, Intellisense silently fails, producing an error only visible within the developer console.

**To Reproduce**
1. Install the latest edition of VSCode under the user directory in Windows 10 (`C:\Users\<username>\AppData\Local\Programs\Microsoft VS Code`)
2. Install **AutoHotkey Plus Plus** extension within VSCode
3. Configure the extension to point to the proper execute/compile paths and ensure Intellisense is enabled
4. Create a file with the sole contents being `sleep 100`
5. Open Developer Tools within VSCode
6. Hover over "`Sleep`" and observe the generated error in the console of the developer tools.

**Expected behavior**
An intellisense view should open detailing the `Sleep` function, when a user hovers over said function.

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10 Home
 - Version 10.0.18363 Build 18363

**VSCode**
- Version: 1.52.0 (user setup)
- Commit: 940b5f4bb5fa47866a54529ed759d95d09ee80be
- Date: 2020-12-10T22:45:11.850Z
- Electron: 9.3.5
- Chrome: 83.0.4103.122
- Node.js: 12.14.1
- V8: 8.3.110.13-electron.0
- OS: Windows_NT x64 10.0.18363
- Installation directory: `C:\Users\mrand\AppData\Local\Programs\Microsoft VS Code`

**AutoHotkey**
- Version: 1.1.33.02
- Installation directory: `D:\Program Files\AutoHotkey`

**Produced error**
```
  ERR Illegal argument: value: Error: Illegal argument: value
	at Object.t.illegalArgument (c:\Users\mrand\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:11:10)
	at new o (c:\Users\mrand\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:302:37)
	at new P (c:\Users\mrand\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:548:49)
	at new P (c:\Users\mrand\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:531:904)
	at AhkHoverProvider.tryGetSnippetHover (c:\Users\mrand\.vscode\extensions\mark-wiemer.vscode-autohotkey-plus-plus-2.5.12\out\provider\ahkHoverProvider.js:46:29)
	at AhkHoverProvider.<anonymous> (c:\Users\mrand\.vscode\extensions\mark-wiemer.vscode-autohotkey-plus-plus-2.5.12\out\provider\ahkHoverProvider.js:24:39)
	at Generator.next (<anonymous>)
	at c:\Users\mrand\.vscode\extensions\mark-wiemer.vscode-autohotkey-plus-plus-2.5.12\out\provider\ahkHoverProvider.js:8:71
	at new Promise (<anonymous>)
	at __awaiter (c:\Users\mrand\.vscode\extensions\mark-wiemer.vscode-autohotkey-plus-plus-2.5.12\out\provider\ahkHoverProvider.js:4:12)
	at AhkHoverProvider.provideHover (c:\Users\mrand\.vscode\extensions\mark-wiemer.vscode-autohotkey-plus-plus-2.5.12\out\provider\ahkHoverProvider.js:22:16)
	at c:\Users\mrand\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:753:757
	at c:\Users\mrand\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:52:1010
	at new Promise (<anonymous>)
	at Object.t.asPromise (c:\Users\mrand\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:52:982)
	at S.provideHover (c:\Users\mrand\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:753:728)
	at c:\Users\mrand\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:775:165
	at q._withAdapter (c:\Users\mrand\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:772:10)
	at q.$provideHover (c:\Users\mrand\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:775:143)
	at m._doInvokeHandler (c:\Users\mrand\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:892:926)
	at m._invokeHandler (c:\Users\mrand\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:892:618)
	at m._receiveRequest (c:\Users\mrand\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:891:201)
	at m._receiveOneMessage (c:\Users\mrand\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:890:6)
	at c:\Users\mrand\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:888:136
	at l.fire (c:\Users\mrand\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:801)
	at v.fire (c:\Users\mrand\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:233:787)
	at c:\Users\mrand\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:1094:104
	at l.fire (c:\Users\mrand\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:801)
	at v.fire (c:\Users\mrand\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:233:787)
	at t.PersistentProtocol._receiveMessage (c:\Users\mrand\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:238:1004)
	at c:\Users\mrand\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:235:927
	at l.fire (c:\Users\mrand\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:801)
	at p.acceptChunk (c:\Users\mrand\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:231:195)
	at c:\Users\mrand\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:230:547
	at Socket.t (c:\Users\mrand\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:240:822)
	at Socket.emit (events.js:223:5)
	at addChunk (_stream_readable.js:309:12)
	at readableAddChunk (_stream_readable.js:290:11)
	at Socket.Readable.push (_stream_readable.js:224:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

**Comment by fade2gray** [comment]
I can confirm this and the same happens with cweijan's AutoHotkey Plus.

Has this anything to do with no longer getting popup descriptions from `snippets\ahk.json`  when hoving over directives, built-in variables and functions etc.?

**Comment by mark-wiemer** [comment]
Great find, and thanks for the detailed report! From your log, it's easy to see that this has to do with the `null` argument passed to the `MarkdownString` constructor in [`ahkHoverProvider.tryGetSnippetHover`](https://github.com/mark-wiemer/vscode-autohotkey-plus-plus/blob/37074f8d703e9ab2f8319bf65d0da70a1457d09c/src/providers/ahkHoverProvider.ts#L65). I have a partial fix in local, but it looks like there is at least one other related failure.
