### ISSUE TITLE
Investigate failing tests

### ISSUE THREAD

**Issue by mark-wiemer** [mark-wiemer/vscode-autohotkey-plus-plus#178]
Somehow the tests passed in #177 but after merging the tests are now failing in main :(

```
~/repos/vscode-autohotkey-plus-plus ((1ad0ef0...))
$ npm run test
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> vscode-autohotkey-plus-plus@2.8.3 pretest
> npm run compile

npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> vscode-autohotkey-plus-plus@2.8.3 compile
> npm run compile_ts && npm run compile_grammar

npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> vscode-autohotkey-plus-plus@2.8.3 compile_ts
> tsc -p ./

npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> vscode-autohotkey-plus-plus@2.8.3 compile_grammar
> js-yaml syntaxes/ahk.tmLanguage.yaml > syntaxes/ahk.tmLanguage.json


> vscode-autohotkey-plus-plus@2.8.3 test
> npm run test_unit && npm run test_grammar_inner

npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> vscode-autohotkey-plus-plus@2.8.3 test_unit
> node ./out/test/runTest.js

Found C:\Users\markw\repos\vscode-autohotkey-plus-plus\.vscode-test\vscode-win32-archive-1.69.2. Skipping download.


[main 2022-07-20T03:34:15.103Z] update#setState idle

[7068:0719/203415.127:ERROR:cache_util_win.cc(20)] Unable to move the cache: Access is denied. (0x5)
[7068:0719/203415.127:ERROR:cache_util.cc(146)] Unable to move cache folder C:\Users\markw\AppData\Roaming\Code\GPUCache to C:\Users\markw\AppData\Roaming\Code\old_GPUCache_000
[7068:0719/203415.127:ERROR:disk_cache.cc(186)] Unable to create cache
[7068:0719/203415.127:ERROR:shader_disk_cache.cc(612)] Shader Cache Creation failed: -2

[7068:0719/203418.055:ERROR:service_worker_storage.cc(1904)] Failed to delete the database: Database IO error

[main 2022-07-20T03:34:21.799Z] Starting extension host with pid 6448 (fork() took 13 ms).

Loading development extension at c:\Users\markw\repos\vscode-autohotkey-plus-plus



  Code utils

    purify

      1) foo("; not comment") => foo("")

      2) MsgBox, { ; comment with close brace } => MsgBox

      3) MsgBox % "; not comment" => MsgBox

      4) str = "`; not comment" => str = ""

      5) str = "; comment with double quote" => str = ""

      ✔ str = "; comment => str = "

      6) Gui, %id%: Color, % color => Gui

      7) Send(Gui) => Send(Gui)

      ✔ Send(foo) => Send(foo)

      8) foo(Gui) => foo(Gui)

  Extension

    ✔ Sample test

  Formatter

    ✔ Format 25-multiline-string (350ms)

    ✔ Format 58-parentheses-indentation (165ms)

    ✔ Format 72-paren-hotkey (44ms)

    ✔ Format ahk-explorer (308ms)

    ✔ Format demo (200ms)

    ✔ Format insert-spaces-false (57ms)

    ✔ Format tab-size-2 (92ms)

  FormattingProvider utils

    hasMoreCloseParens

      ✔ (')') => true

      ✔ ('()') => false

      ✔ ('())') => true

      ✔ ('(::') => false

      ✔ ('') => false

    hasMoreOpenParens

      ✔ ('(') => true

      ✔ ('()') => false

      ✔ ('(()') => true

      ✔ ('(::') => true

      ✔ ('') => false

  20 passing (1s)

  8 failing

  1) Code utils
       purify
         foo("; not comment") => foo(""):

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ 'foo("'
- 'foo("")'
        ^
      + expected - actual

      -foo("
      +foo("")

        at Context.<anonymous> (c:\Users\markw\repos\vscode-autohotkey-plus-plus\out\test\suite\common\codeUtil.test.js:56:24)
        at processImmediate (node:internal/timers:464:21)


  2) Code utils
       purify
         MsgBox, { ; comment with close brace } => MsgBox:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ 'MsgBox, { '
- 'MsgBox'
         ^
      + expected - actual

      -MsgBox, {
      +MsgBox

        at Context.<anonymous> (c:\Users\markw\repos\vscode-autohotkey-plus-plus\out\test\suite\common\codeUtil.test.js:56:24)
        at processImmediate (node:internal/timers:464:21)

  3) Code utils
       purify
         MsgBox % "; not comment" => MsgBox:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ 'MsgBox "'
- 'MsgBox'
         ^
      + expected - actual

      -MsgBox "
      +MsgBox

        at Context.<anonymous> (c:\Users\markw\repos\vscode-autohotkey-plus-plus\out\test\suite\common\codeUtil.test.js:56:24)
        at processImmediate (node:internal/timers:464:21)

  4) Code utils
       purify
         str = "`; not comment" => str = "":

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ 'str = "`'
- 'str = ""'
          ^
      + expected - actual

      -str = "`
      +str = ""

        at Context.<anonymous> (c:\Users\markw\repos\vscode-autohotkey-plus-plus\out\test\suite\common\codeUtil.test.js:56:24)
        at processImmediate (node:internal/timers:464:21)


Error: 8 tests failed.
        at c:\Users\markw\repos\vscode-autohotkey-plus-plus\out\test\suite\index.js:26:27
        at done (c:\Users\markw\repos\vscode-autohotkey-plus-plus\node_modules\mocha\lib\mocha.js:1009:7)

  5) Code utils
       purify
         str = "; comment with double quote" => str = "":

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ 'str = "'
- 'str = ""'
          ^
      + expected - actual

      -str = "
      +str = ""

        at Context.<anonymous> (c:\Users\markw\repos\vscode-autohotkey-plus-plus\out\test\suite\common\codeUtil.test.js:56:24)
        at processImmediate (node:internal/timers:464:21)

  6) Code utils
       purify
         Gui, %id%: Color, % color => Gui:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:

'' !== 'Gui'

      + expected - actual

      +Gui

        at Context.<anonymous> (c:\Users\markw\repos\vscode-autohotkey-plus-plus\out\test\suite\common\codeUtil.test.js:56:24)
        at processImmediate (node:internal/timers:464:21)

  7) Code utils
       purify
         Send(Gui) => Send(Gui):

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ 'Send('
- 'Send(Gui)'
        ^
      + expected - actual

      -Send(
      +Send(Gui)

        at Context.<anonymous> (c:\Users\markw\repos\vscode-autohotkey-plus-plus\out\test\suite\common\codeUtil.test.js:56:24)
        at processImmediate (node:internal/timers:464:21)

  8) Code utils
       purify
         foo(Gui) => foo(Gui):

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ 'foo('
- 'foo(Gui)'
       ^
      + expected - actual

      -foo(
      +foo(Gui)

        at Context.<anonymous> (c:\Users\markw\repos\vscode-autohotkey-plus-plus\out\test\suite\common\codeUtil.test.js:56:24)
        at processImmediate (node:internal/timers:464:21)


[main 2022-07-20T03:34:24.670Z] Extension host with pid 6448 exited with code: 0, signal: null.

[main 2022-07-20T03:34:24.673Z] Waiting for extension host with pid 6448 to exit.

Cannot call write after a stream was destroyed: Error: Cannot call write after a stream was destroyed
    at __node_internal_captureLargerStackTrace (node:internal/errors:464:5)
    at new NodeError (node:internal/errors:371:5)
    at errorBuffer (node:internal/streams/writable:517:14)
    at afterWrite (node:internal/streams/writable:501:5)
    at onwrite (node:internal/streams/writable:477:7)
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:91:12)

Exit code:   1
Done

Failed to run tests
```

**Comment by mark-wiemer** [comment]
It's because the `out` folder isn't being cleared! We need to clear this folder before ever compiling or running the tests
